language: objective-c
osx_image: xcode9.2
script: xcodebuild -project TweenController.xcodeproj -scheme TweenController -sdk iphonesimulator -destination 'platform=iOS Simulator,id=48099C45-0EB1-4FDF-8C6A-360266EB796B,OS=11.2' test
after_success:
- bash <(curl -s https://codecov.io/bash) -J '^TweenController$'
