language: objective-c
osx_image: xcode8.2
script: xcodebuild -project TweenController.xcodeproj -scheme TweenController -sdk iphonesimulator -destination 'platform=iOS Simulator,id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12,OS=10.2' test
after_success:
- bash <(curl -s https://codecov.io/bash) -J '^TweenController$'
